server:
  port: 8234

spring:
  data:
    mongodb:
      uri: mongodb+srv://jvbaprof:dgIvzrhWsaYCJmB3@jvcluster.rsfoux2.mongodb.net/?retryWrites=true&w=majority&appName=JvCluster
      database: db_water
  security:
    user:
      name: admin
      password: admin
