name: Java CI with Maven and MongoDB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MONGODB_URI: ${{ secrets.MONGODB_ATLAS_URI }}
  SPRING_DATA_MONGODB_URI: ${{ secrets.MONGODB_ATLAS_URI }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update db url
      run: sed -i 's/<db_url>/${{ secrets.MONGODB_ATLAS_URI }}/' src/main/resources/application.yml
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Run unit tests
      run: mvn test
      env:
        MONGODB_URI: ${{ secrets.MONGODB_ATLAS_URI }}
        SPRING_DATA_MONGODB_URI: ${{ secrets.MONGODB_ATLAS_URI }}
